export const copy = {
  // Navigation & Headers
  soapNote: "SOAP Note",
  soapNoteDesc: "Document subjective, objective, assessment, and plan",
  rxPrescriptions: "RX - Prescriptions", 
  rxDesc: "Create and manage prescription orders",
  labOrders: "Lab Orders",
  labOrdersDesc: "Laboratory tests and orders",
  intakeForm: "Intake Form", 
  intakeFormDesc: "Complete patient intake information",
  diagnosesTitle: "Diagnoses, Medications & Allergies",
  diagnosesDesc: "Current patient conditions and treatments",
  previousResults: "Previous Labs & Imaging Results",
  previousResultsDesc: "Historical test results and imaging studies",

  // Buttons & Actions
  save: "Save",
  cancel: "Cancel", 
  insert: "Insert",
  preview: "Preview",
  addOrder: "Add Order",
  createRefill: "Create refill",
  edit: "Edit",
  remove: "Remove",
  orderNewLab: "Order new lab",
  sendIntakeForm: "Send intake form to patient",
  joinMeeting: "Join meeting",
  finishAppointment: "Finish appointment",

  // Form Labels & Fields
  chiefComplaint: "Chief Complaint / History of Present Illness",
  chiefComplaintPlaceholder: "Reported concerns, symptom history, relevant context",
  currentMedications: "Current Medications",
  currentMedsPlaceholder: "Prescription medications with dose and frequency", 
  supplementsOtc: "Supplements & OTC",
  supplementsPlaceholder: "Supplements or OTC with dose and frequency",
  allergies: "Allergies",
  allergiesPlaceholder: "Allergies and reactions. NKDA if none",
  clinicalObservations: "Clinical Observations",
  observationsPlaceholder: "Summarize exam and general appearance",
  assessment: "Assessment / Problem List", 
  assessmentPlaceholder: "Key clinical issues under consideration",
  differential: "Differential Diagnosis",
  differentialPlaceholder: "Possible alternate explanations",
  plan: "Plan / Patient Instructions",
  planPlaceholder: "Diagnostic tests, prescriptions, lifestyle guidance, follow-up instructions",
  acuteDiagnosis: "Acute Diagnosis",
  acuteDiagnosisPlaceholder: "Confirmed diagnosis with ICD-10 codes",
  comorbidities: "Comorbidities / Contributing Conditions",
  comorbiditiesPlaceholder: "Chronic or contributing factors",

  // Measurements
  waist: "Waist (in)",
  hip: "Hip (in)", 
  height: "Height",
  weight: "Weight (lbs)",
  bmi: "BMI (auto)",
  feet: "feet",
  inches: "inches",

  // Medical Info
  medicineName: "Medicine name",
  medicineNamePlaceholder: "Enter medicine name",
  formulation: "Formulation",
  route: "Route", 
  quantity: "Quantity",
  frequency: "Frequency",
  duration: "Duration",
  unit: "Unit",
  totalQty: "Total Qty",
  refills: "Refills",
  action: "Action",
  prnAsNeeded: "PRN (as needed)",
  location: "Location",
  substitutions: "Substitutions",
  substitutionsAllowed: "Substitutions allowed",
  noSubstitutions: "No substitutions",
  startDate: "Start date",
  earliestFillDate: "Earliest fill date",
  notesToPatient: "Notes to patient",
  notesToPharmacy: "Notes to pharmacy",
  patientNotesPlaceholder: "Additional instructions for the patient",
  pharmacyNotesPlaceholder: "Additional instructions for the pharmacy",
  orderSummary: "Order Summary",

  // Statuses & Badges
  pending: "Pending",
  active: "Active",
  longTerm: "Long-term", 
  critical: "Critical",
  new: "New",
  requiresAttention: "Requires Attention",

  // Sections
  subjective: "Subjective",
  objective: "Objective", 
  planSection: "Plan",

  // Pharmacy
  partellSpecialty: "Partell specialty pharmacy",
  walgreens: "Walgreens",
  chooseOtherPharmacy: "Choose other pharmacy",
  sendToManager: "Send to manager",
  freedom: "Freedom",
  nearby: "Nearby",

  // Misc
  normal: "Normal",
  routine: "Routine",
  ordered: "Ordered",
  priority: "Priority",
  indication: "Indication",
  collected: "Collected"
} as const;